# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_smooth3d <- function(las, radius, weight, ncpu, pgbar, verbose) {
    .Call(`_lidRalignment_cpp_smooth3d`, las, radius, weight, ncpu, pgbar, verbose)
}

